// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/apercu-ecole.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
      // Une configuration JSON invalide est ignorée au profit de la clé legacy.
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function resolveContext(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data: profile, error } = await supabase.from("profiles").select("ecole_id").eq("id", ctx.getUserId()).maybeSingle();
  if (error) throw new Error(error.message);
  const ecoleId = profile?.ecole_id ?? null;
  if (!ecoleId) throw new Error("Aucune \xE9cole rattach\xE9e \xE0 ce compte.");
  const { data: annee } = await supabase.from("annees_scolaires").select("id, libelle, statut").eq("ecole_id", ecoleId).eq("statut", "active").maybeSingle();
  return {
    supabase,
    ecoleId,
    anneeId: annee?.id ?? null,
    anneeLibelle: annee?.libelle ?? null
  };
}
function fcfa(n) {
  return `${Math.round(n).toLocaleString("fr-FR")} FCFA`;
}

// src/lib/mcp/tools/apercu-ecole.ts
const apercu_ecole_default = defineTool({
  name: "apercu_ecole",
  title: "Aper\xE7u de l'\xE9cole",
  description: "Chiffres cl\xE9s de l'\xE9cole de l'utilisateur : ann\xE9e active, effectifs \xE9l\xE8ves (dont nouveaux), nombre de classes et d'enseignants.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { supabase, ecoleId, anneeId, anneeLibelle } = await resolveContext(ctx);
    const { data: ecole } = await supabase.from("ecoles").select("nom").eq("id", ecoleId).maybeSingle();
    const eleves = supabase.from("eleves").select("id", { count: "exact", head: true }).eq("ecole_id", ecoleId);
    const nouveaux = supabase.from("eleves").select("id", { count: "exact", head: true }).eq("ecole_id", ecoleId).eq("est_nouveau", true);
    const classes = supabase.from("classes").select("id", { count: "exact", head: true }).eq("ecole_id", ecoleId);
    const [r1, r2, r3, r4] = await Promise.all([
      anneeId ? eleves.eq("annee_id", anneeId) : eleves,
      anneeId ? nouveaux.eq("annee_id", anneeId) : nouveaux,
      anneeId ? classes.eq("annee_id", anneeId) : classes,
      supabase.from("enseignants").select("id", { count: "exact", head: true }).eq("ecole_id", ecoleId)
    ]);
    const stats = {
      ecole: ecole?.nom ?? null,
      annee: anneeLibelle,
      eleves: r1.count ?? 0,
      nouveaux: r2.count ?? 0,
      classes: r3.count ?? 0,
      enseignants: r4.count ?? 0
    };
    const text = [
      `${stats.ecole ?? "\xC9cole"} \u2014 ann\xE9e ${stats.annee ?? "non d\xE9finie"}`,
      `\xC9l\xE8ves inscrits : ${stats.eleves} (dont ${stats.nouveaux} nouveaux)`,
      `Classes : ${stats.classes}`,
      `Enseignants : ${stats.enseignants}`
    ].join("\n");
    return { content: [{ type: "text", text }], structuredContent: stats };
  }
});

// src/lib/mcp/tools/lister-classes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
const lister_classes_default = defineTool2({
  name: "lister_classes",
  title: "Lister les classes",
  description: "Liste les classes de l'ann\xE9e scolaire active avec leur effectif et leur capacit\xE9.",
  inputSchema: {
    recherche: z.string().describe("Filtre optionnel sur le nom de la classe.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ recherche }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { supabase, ecoleId, anneeId, anneeLibelle } = await resolveContext(ctx);
    let q = supabase.from("classes").select("id, nom, capacite, cycles(nom)").eq("ecole_id", ecoleId).order("nom");
    if (anneeId) q = q.eq("annee_id", anneeId);
    if (recherche?.trim()) q = q.ilike("nom", `%${recherche.trim().replace(/[%,]/g, " ")}%`);
    const { data: classes, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let elevesQuery = supabase.from("eleves").select("classe_id").eq("ecole_id", ecoleId);
    if (anneeId) elevesQuery = elevesQuery.eq("annee_id", anneeId);
    const { data: eleves } = await elevesQuery;
    const counts = /* @__PURE__ */ new Map();
    for (const e of eleves ?? []) {
      if (e.classe_id) counts.set(e.classe_id, (counts.get(e.classe_id) ?? 0) + 1);
    }
    const rows = (classes ?? []).map((c) => ({
      classe: c.nom,
      cycle: c.cycles?.nom ?? null,
      effectif: counts.get(c.id) ?? 0,
      capacite: c.capacite ?? null
    }));
    const text = rows.length ? `Ann\xE9e ${anneeLibelle ?? "active"}
` + rows.map((r) => `${r.classe} (${r.cycle ?? "\u2014"}) : ${r.effectif} \xE9l\xE8ves${r.capacite ? ` / ${r.capacite}` : ""}`).join("\n") : "Aucune classe trouv\xE9e.";
    return { content: [{ type: "text", text }], structuredContent: { classes: rows } };
  }
});

// src/lib/mcp/tools/point-encaissements.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
const point_encaissements_default = defineTool3({
  name: "point_encaissements",
  title: "Point des encaissements",
  description: "Total des encaissements de scolarit\xE9 (paiements non annul\xE9s) sur une p\xE9riode, avec la r\xE9partition par mode de paiement.",
  inputSchema: {
    date_debut: z2.string().describe("Date de d\xE9but incluse, format AAAA-MM-JJ."),
    date_fin: z2.string().describe("Date de fin incluse, format AAAA-MM-JJ.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date_debut, date_fin }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const iso = /^\d{4}-\d{2}-\d{2}$/;
    if (!iso.test(date_debut) || !iso.test(date_fin)) {
      return { content: [{ type: "text", text: "Dates attendues au format AAAA-MM-JJ." }], isError: true };
    }
    const { supabase, ecoleId } = await resolveContext(ctx);
    const { data, error } = await supabase.from("paiements").select("montant, mode, date_paiement, annule_le").eq("ecole_id", ecoleId).gte("date_paiement", date_debut).lte("date_paiement", date_fin).is("annule_le", null).limit(5e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const total = rows.reduce((s, p) => s + Number(p.montant || 0), 0);
    const parMode = {};
    for (const p of rows) parMode[p.mode] = (parMode[p.mode] ?? 0) + Number(p.montant || 0);
    const text = [
      `Encaissements du ${date_debut} au ${date_fin}`,
      `Nombre de paiements : ${rows.length}`,
      `Total : ${fcfa(total)}`,
      ...Object.entries(parMode).map(([m, v]) => `\xB7 ${m} : ${fcfa(v)}`)
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { periode: { date_debut, date_fin }, nombre: rows.length, total, par_mode: parMode }
    };
  }
});

// src/lib/mcp/tools/rechercher-eleves.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
const rechercher_eleves_default = defineTool4({
  name: "rechercher_eleves",
  title: "Rechercher des \xE9l\xE8ves",
  description: "Recherche les \xE9l\xE8ves de l'\xE9cole de l'utilisateur par nom, pr\xE9nom ou matricule. Retourne matricule, nom, classe et statut.",
  inputSchema: {
    recherche: z3.string().describe("Nom, pr\xE9nom ou matricule (partiel accept\xE9)."),
    limite: z3.number().int().describe("Nombre maximum de r\xE9sultats (d\xE9faut 20, max 100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ recherche, limite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { supabase, ecoleId, anneeId } = await resolveContext(ctx);
    const max = Math.min(Math.max(limite ?? 20, 1), 100);
    const term = recherche.trim().replace(/[%,]/g, " ");
    let query = supabase.from("eleves").select("matricule, nom, prenom, statut, est_nouveau, sexe, classes(nom)").eq("ecole_id", ecoleId).or(`nom.ilike.%${term}%,prenom.ilike.%${term}%,matricule.ilike.%${term}%`).order("nom").limit(max);
    if (anneeId) query = query.eq("annee_id", anneeId);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((e) => ({
      matricule: e.matricule,
      nom: `${e.nom} ${e.prenom}`.trim(),
      classe: e.classes?.nom ?? null,
      statut: e.statut,
      nouveau: e.est_nouveau,
      sexe: e.sexe
    }));
    const text = rows.length ? rows.map((r) => `${r.matricule} \u2014 ${r.nom} \u2014 ${r.classe ?? "sans classe"} \u2014 ${r.statut}`).join("\n") : "Aucun \xE9l\xE8ve trouv\xE9.";
    return { content: [{ type: "text", text }], structuredContent: { eleves: rows } };
  }
});

// src/lib/mcp/tools/situation-scolarite.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
const situation_scolarite_default = defineTool5({
  name: "situation_scolarite_eleve",
  title: "Situation de scolarit\xE9 d'un \xE9l\xE8ve",
  description: "Retourne la situation financi\xE8re de scolarit\xE9 d'un \xE9l\xE8ve (total d\xFB, encaiss\xE9, reste \xE0 payer) et le d\xE9tail de ses tranches.",
  inputSchema: {
    matricule: z4.string().describe("Matricule exact de l'\xE9l\xE8ve.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ matricule }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const { supabase, ecoleId } = await resolveContext(ctx);
    const { data: eleve, error } = await supabase.from("eleves").select("id, matricule, nom, prenom, statut, classes(nom)").eq("ecole_id", ecoleId).eq("matricule", matricule.trim()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!eleve) {
      return { content: [{ type: "text", text: `Aucun \xE9l\xE8ve avec le matricule ${matricule}.` }], isError: true };
    }
    const { data: tranches } = await supabase.from("tranches").select("numero, label, montant, paye, statut, echeance").eq("ecole_id", ecoleId).eq("eleve_id", eleve.id).order("numero");
    const list = tranches ?? [];
    const total = list.reduce((s, t) => s + Number(t.montant || 0), 0);
    const paye = list.reduce((s, t) => s + Number(t.paye || 0), 0);
    const reste = Math.max(total - paye, 0);
    const nom = `${eleve.nom} ${eleve.prenom}`.trim();
    const text = [
      `${nom} (${eleve.matricule}) \u2014 ${eleve.classes?.nom ?? "sans classe"}`,
      `Total d\xFB : ${fcfa(total)} \xB7 Encaiss\xE9 : ${fcfa(paye)} \xB7 Reste : ${fcfa(reste)}`,
      ...list.map(
        (t) => `Tranche ${t.numero} ${t.label} \u2014 ${fcfa(Number(t.paye))}/${fcfa(Number(t.montant))} (${t.statut}, \xE9ch\xE9ance ${t.echeance})`
      )
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        eleve: { matricule: eleve.matricule, nom, classe: eleve.classes?.nom ?? null },
        total_du: total,
        total_encaisse: paye,
        reste_a_payer: reste,
        tranches: list
      }
    };
  }
});

// src/lib/mcp/index.ts
const projectRef = "yvsnokvgxqtpqkuizsfo";
const mcp_default = defineMcp({
  name: "la-providence",
  title: "La Providence",
  version: "0.1.0",
  instructions: "Outils de lecture pour la plateforme de gestion scolaire La Providence. Utilisez `apercu_ecole` pour les chiffres cl\xE9s, `lister_classes` pour les effectifs, `rechercher_eleves` pour retrouver un \xE9l\xE8ve et son matricule, `situation_scolarite_eleve` pour son solde de scolarit\xE9, et `point_encaissements` pour le point de caisse sur une p\xE9riode. Toutes les donn\xE9es sont limit\xE9es \xE0 l'\xE9cole et aux droits de l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    apercu_ecole_default,
    lister_classes_default,
    rechercher_eleves_default,
    situation_scolarite_default,
    point_encaissements_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
